#include "river_hdl.h"

#include <algorithm>
#include <fstream>
#include <sstream>
#include <unordered_map>
#include <unordered_set>

#include "pdk_map.h"

namespace river {

namespace {

std::string node_name(uint16_t node_id) {
    std::ostringstream out;
    out << "node_" << node_id;
    return out.str();
}

std::string wire_name(uint16_t src, uint16_t dest) {
    std::ostringstream out;
    out << "wire_" << src << "_" << dest;
    return out.str();
}

std::string port_name(uint16_t node_id) {
    std::ostringstream out;
    out << "up_" << node_id;
    return out.str();
}

} // namespace

bool emit_verilog(
    const std::vector<MapNodeEntry>& nodes,
    const std::vector<LinkFlowEntry>& links,
    uint32_t epoch,
    const std::string& out_path
) {
    std::ofstream out(out_path, std::ios::out | std::ios::trunc);
    if (!out.is_open()) {
        return false;
    }

    out << "// RIVER-LANG HDL emitted for epoch 0x" << std::hex << epoch << std::dec << "\n";
    out << "// Generated by river_hdl backend\n\n";

    std::unordered_set<uint16_t> upstream_outputs;
    std::unordered_set<uint16_t> upstream_inputs;
    for (const auto& link : links) {
        if (link.is_upstream) {
            upstream_outputs.insert(link.src_node);
            upstream_inputs.insert(link.dest_node);
        }
    }

    std::vector<std::string> port_list;
    port_list.reserve(upstream_outputs.size() + upstream_inputs.size());

    for (uint16_t node_id : upstream_inputs) {
        port_list.push_back(port_name(node_id));
    }
    for (uint16_t node_id : upstream_outputs) {
        if (upstream_inputs.find(node_id) == upstream_inputs.end()) {
            port_list.push_back(port_name(node_id));
        }
    }

    out << "module river_epoch_" << std::hex << epoch << std::dec << "(";
    for (size_t i = 0; i < port_list.size(); ++i) {
        out << port_list[i];
        if (i + 1 < port_list.size()) {
            out << ", ";
        }
    }
    out << ");\n";

    for (uint16_t node_id : upstream_inputs) {
        out << "  input " << port_name(node_id) << ";\n";
    }
    for (uint16_t node_id : upstream_outputs) {
        if (upstream_inputs.find(node_id) != upstream_inputs.end()) {
            out << "  inout " << port_name(node_id) << ";\n";
        } else {
            out << "  output " << port_name(node_id) << ";\n";
        }
    }

    for (const auto& link : links) {
        if (!link.is_upstream) {
            out << "  " << RIVER_CELL_WIRE << " " << wire_name(link.src_node, link.dest_node) << ";\n";
        }
    }

    out << "\n";

    std::unordered_map<uint16_t, bool> has_up_port;
    for (uint16_t node_id : upstream_outputs) {
        has_up_port[node_id] = true;
    }
    for (uint16_t node_id : upstream_inputs) {
        has_up_port[node_id] = true;
    }

    for (const auto& node : nodes) {
        const std::string inst_name = node_name(node.node_id);
        out << "  " << RIVER_CELL_NODE << " #(.ADDR(32'h";
        out << std::hex << node.address << std::dec << ")) " << inst_name << " (";

        bool first = true;
        if (has_up_port.find(node.node_id) != has_up_port.end()) {
            out << "." << RIVER_CELL_UPSTREAM_PORT << "(" << port_name(node.node_id) << ")";
            first = false;
        }

        for (const auto& link : links) {
            if (!link.is_upstream && link.src_node == node.node_id) {
                if (!first) {
                    out << ", ";
                }
                out << "." << RIVER_CELL_DOWNSTREAM_PORT << "(" << wire_name(link.src_node, link.dest_node) << ")";
                first = false;
            }
            if (!link.is_upstream && link.dest_node == node.node_id) {
                if (!first) {
                    out << ", ";
                }
                out << "." << RIVER_CELL_DOWNSTREAM_PORT << "(" << wire_name(link.src_node, link.dest_node) << ")";
                first = false;
            }
        }

        out << ");\n";
    }

    out << "\nendmodule\n";
    return true;
}

} // namespace river
